### ISSUE TITLE
CI failure: ImportError: cannot import name 'filefind' from 'traitlets.utils'

### ISSUE THREAD

**Issue by muupan** [pfnet/pfrl#162]
https://ci.preferred.jp/pfrl.cpu.examples/88391/
```
00:09:19.287659 STDERR 1944] | + xvfb-run '--server-args=-screen 0 1280x800x24' jupyter nbconvert --to notebook --execute examples/quickstart/quickstart.ipynb --ExecutePreprocessor.timeout=600 |  
-- | -- | --
00:09:20.220466 STDOUT 1944] | [NbConvertApp] Converting notebook examples/quickstart/quickstart.ipynb to notebook | 1.1s
00:09:21.275059 STDOUT 1944] | Traceback (most recent call last): |  
00:09:21.275074 STDOUT 1944] | File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main |  
00:09:21.275086 STDOUT 1944] | "__main__", mod_spec) |  
00:09:21.275367 STDOUT 1944] | File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code |  
00:09:21.275371 STDOUT 1944] | exec(code, run_globals) |  
00:09:21.275377 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module> |  
00:09:21.275426 STDOUT 1944] | from ipykernel import kernelapp as app |  
00:09:21.275428 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 33, in <module> |  
00:09:21.275436 STDOUT 1944] | from traitlets.utils import filefind |  
00:09:21.275484 STDOUT 1944] | ImportError: cannot import name 'filefind' from 'traitlets.utils' (/opt/conda/lib/python3.7/site-packages/traitlets/utils/__init__.py) |  
00:09:21.840427 STDOUT 1944] | Traceback (most recent call last): |  
00:09:21.840441 STDOUT 1944] | File "/opt/conda/bin/jupyter-nbconvert", line 8, in <module> |  
00:09:21.840453 STDOUT 1944] | sys.exit(main()) |  
00:09:21.840718 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance |  
00:09:21.840722 STDOUT 1944] | return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs) |  
00:09:21.840728 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance |  
00:09:21.840778 STDOUT 1944] | app.start() |  
00:09:21.840781 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 361, in start |  
00:09:21.840834 STDOUT 1944] | self.convert_notebooks() |  
00:09:21.840836 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 533, in convert_notebooks |  
00:09:21.840841 STDOUT 1944] | self.convert_single_notebook(notebook_filename) |  
00:09:21.840876 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 498, in convert_single_notebook |  
00:09:21.840879 STDOUT 1944] | output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer) |  
00:09:21.840884 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 427, in export_single_notebook |  
00:09:21.840934 STDOUT 1944] | output, resources = self.exporter.from_filename(notebook_filename, resources=resources) |  
00:09:21.840936 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 186, in from_filename |  
00:09:21.840941 STDOUT 1944] | return self.from_file(f, resources=resources, **kw) |  
00:09:21.840989 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 204, in from_file |  
00:09:21.840991 STDOUT 1944] | return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw) |  
00:09:21.840997 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node |  
00:09:21.841045 STDOUT 1944] | nb_copy, resources = super().from_notebook_node(nb, resources, **kw) |  
00:09:21.841047 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node |  
00:09:21.841053 STDOUT 1944] | nb_copy, resources = self._preprocess(nb_copy, resources) |  
00:09:21.841097 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 323, in _preprocess |  
00:09:21.841101 STDOUT 1944] | nbc, resc = preprocessor(nbc, resc) |  
00:09:21.841108 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__ |  
00:09:21.841150 STDOUT 1944] | return self.preprocess(nb, resources) |  
00:09:21.841153 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 80, in preprocess |  
00:09:21.841158 STDOUT 1944] | with self.setup_kernel(): |  
00:09:21.841211 STDOUT 1944] | File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__ |  
00:09:21.841214 STDOUT 1944] | return next(self.gen) |  
00:09:21.841219 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 461, in setup_kernel |  
00:09:21.841267 STDOUT 1944] | self.start_new_kernel_client() |  
00:09:21.841271 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped |  
00:09:22.174669 STDOUT 1944] | return just_run(coro(*args, **kwargs)) |  
00:09:22.174672 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run |  
00:09:22.174677 STDOUT 1944] | return loop.run_until_complete(coro) |  
00:09:22.174715 STDOUT 1944] | File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete |  
00:09:22.174717 STDOUT 1944] | return future.result() |  
00:09:22.174722 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 432, in async_start_new_kernel_client |  
00:09:22.174755 STDOUT 1944] | await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout)) |  
00:09:22.174764 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 96, in ensure_async |  
00:09:22.174769 STDOUT 1944] | result = await obj |  
00:09:22.174800 STDOUT 1944] | File "/opt/conda/lib/python3.7/site-packages/jupyter_client/client.py", line 180, in _async_wait_for_ready |  
00:09:22.174803 STDOUT 1944] | raise RuntimeError("Kernel died before replying to kernel_info") |  
00:09:22.174807 STDOUT 1944] | RuntimeError: Kernel died before replying to kernel_info
```

**Comment by muupan** [comment]
resolved by #169
