### ISSUE TITLE
CI failure in pfrl.cpu.examples: ImportError: cannot import name 'Callable' from 'traitlets'

### ISSUE THREAD

**Issue by muupan** [pfnet/pfrl#168]
https://ci.preferred.jp/pfrl.cpu.examples/96611/#L3639 (executed from latest master efb9056579ff01303c516d56e5e586bc598b6715)
```
00:07:39.468818 STDERR 1211] | + xvfb-run '--server-args=-screen 0 1280x800x24' jupyter nbconvert --to notebook --execute examples/quickstart/quickstart.ipynb --ExecutePreprocessor.timeout=600 |  
-- | -- | --
00:07:39.851064 STDOUT 1211] | Traceback (most recent call last): |  
00:07:39.851076 STDOUT 1211] | File "/opt/conda/bin/jupyter-nbconvert", line 5, in <module> |  
00:07:39.851088 STDOUT 1211] | from nbconvert.nbconvertapp import main |  
00:07:39.851398 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module> |  
00:07:39.851401 STDOUT 1211] | from .exporters import * |  
00:07:39.851406 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 4, in <module> |  
00:07:39.851469 STDOUT 1211] | from .slides import SlidesExporter |  
00:07:39.851471 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/slides.py", line 12, in <module> |  
00:07:39.851476 STDOUT 1211] | from ..preprocessors.base import Preprocessor |  
00:07:39.851531 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/__init__.py", line 10, in <module> |  
00:07:39.851533 STDOUT 1211] | from .execute import ExecutePreprocessor |  
00:07:39.851540 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 8, in <module> |  
00:07:39.851578 STDOUT 1211] | from nbclient import NotebookClient, execute as _execute |  
00:07:39.851616 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbclient/__init__.py", line 6, in <module> |  
00:07:39.851618 STDOUT 1211] | from .client import NotebookClient, execute  # noqa: F401 |  
00:07:39.851623 STDOUT 1211] | File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 18, in <module> |  
00:07:39.851683 STDOUT 1211] | from traitlets import ( |  
00:07:39.851685 STDOUT 1211] | ImportError: cannot import name 'Callable' from 'traitlets' (/opt/conda/lib/python3.7/site-packages/traitlets/__init__.py)
```

**Comment by muupan** [comment]
This seems caused by a version incompatibility of `traitlets`: https://ci.preferred.jp/pfrl.cpu.examples/96611/#L2229
```
00:03:06.395347 STDERR 1211] | ERROR: ipykernel 6.9.1 has requirement traitlets<6.0,>=5.1.0, but you'll have traitlets 4.3.3 which is incompatible. |  
-- | -- | --
00:03:06.395548 STDERR 1211] | ERROR: nbclient 0.5.13 has requirement traitlets>=5.0.0, but you'll have traitlets 4.3.3 which is incompatible. |  
00:03:06.395551 STDERR 1211] | ERROR: nbconvert 6.4.2 has requirement traitlets>=5.0, but you'll have traitlets 4.3.3 which is incompatible.
```

When `traitlets==5.1.1` is installed explicitly, the error disappears:
```
diff --git a/.pfnci/run.sh b/.pfnci/run.sh
index b16356b6..5e5dbee3 100644
--- a/.pfnci/run.sh
+++ b/.pfnci/run.sh
@@ -75,7 +75,7 @@ main() {
   # pytest does not run with attrs==19.2.0 (https://github.com/pytest-dev/pytest/issues/3280)  # NOQA
   "${PYTHON}" -m pip install \
       'pytest==4.1.1' 'attrs==19.1.0' 'pytest-xdist==1.26.1' \
-      'gym[atari,classic_control]==0.19.0' 'optuna' 'zipp==1.0.0' 'pybullet==2.8.1' 'jupyterlab==2.1.5'
+      'gym[atari,classic_control]==0.19.0' 'optuna' 'zipp==1.0.0' 'pybullet==2.8.1' 'jupyterlab==2.1.5' 'traitlets==5.1.1'
```
https://ci.preferred.jp/pfrl.cpu.examples/96621/
